INTERPRETER = python3

default:
	@echo 'Targets:'
	@echo '  run-sequential'
	@echo '  run-async1'
	@echo '  run-async2'

run-sequential:
	$(INTERPRETER) 1_sequential.py

run-async1:
	$(INTERPRETER) 2_async1_coroutines.py

run-async2:
	$(INTERPRETER) 2_async2_tasks.py
